name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '14 3 * * 1'

jobs:
  hassfest:
    name: hassfest
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: hacs
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
